// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_kwZ68o0fS0RpbqFascQ3hgI5bPIlTc',
    appId: '1:532868288845:web:e8cf4c137172436552a704',
    messagingSenderId: '532868288845',
    projectId: 'questure-app',
    authDomain: 'questure-app.firebaseapp.com',
    storageBucket: 'questure-app.appspot.com',
    measurementId: 'G-GDKJ1W9WRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyJ3cbLW3yuItrSmFSwjsL3uPtFSp4C4A',
    appId: '1:532868288845:android:d338c2646f839f4952a704',
    messagingSenderId: '532868288845',
    projectId: 'questure-app',
    storageBucket: 'questure-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvlZcFoRADw1XT0o77a2GHnu0OtaorY50',
    appId: '1:532868288845:ios:121d5a4523ea38fe52a704',
    messagingSenderId: '532868288845',
    projectId: 'questure-app',
    storageBucket: 'questure-app.appspot.com',
    iosBundleId: 'com.example.questure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvlZcFoRADw1XT0o77a2GHnu0OtaorY50',
    appId: '1:532868288845:ios:f10398528b50e29052a704',
    messagingSenderId: '532868288845',
    projectId: 'questure-app',
    storageBucket: 'questure-app.appspot.com',
    iosBundleId: 'com.example.questure.RunnerTests',
  );
}
